### ISSUE TITLE
执行run_data.sh时候报错

### ISSUE THREAD

**Issue by 393846671** [Pelhans/ZASR_tensorflow#3]
Creating manifest data/aishell/manifest ...
Traceback (most recent call last):
  File "data_utils/build_vocab.py", line 19, in <module>
    from utils.utility import add_arguments, print_arguments
ImportError: No module named utility
Build vocabulary failed. Terminated.

貌似这个utils.utility找不到。
我尝试重新安装了utils和utility都没有效果，请问改怎么处理啊

**Comment by Pelhans** [comment]
这个utils.utility是指utils文件夹下的 utility.py 文件，可能是导入路径的问题，我修改一下

**Comment by ckn123** [comment]
怎么修改到 8g GPU 显卡内存  合适？

**Comment by Pelhans** [comment]
> 
> 
> 怎么修改到 8g GPU 显卡内存 合适？

减小batch size
